"""empty message

Revision ID: abcc3d4dac58
Revises: 
Create Date: 2022-04-19 17:28:27.241858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcc3d4dac58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True, comment='ma cong ty'),
    sa.Column('company_name', sa.String(), nullable=True, comment='ten cong ty'),
    sa.Column('description', sa.Text(), nullable=True, comment='mo ta'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_code'), 'company', ['company_code'], unique=True)
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_company_code'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
